[package]
name = "rtunnel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
anyhow = "1.0.98"
