[package]
name = "rtunnel"
version = "0.7.6"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand_core = { version = "0.6.4", features = ["getrandom", "std"] }
base64 = "0.22.1"
sha2 = "0.10.9"
aes-gcm = { version = "0.10.3", features = ["std"] }
hkdf = { version = "0.12.4", features = ["std"] }
bytes = "1.10.1"
aead = { version = "0.5.2", features = ["std", "bytes"] }
log = "0.4.27"
tokio-util = { version = "0.7.15", features = ["rt"] }
socket2 = "0.6.0"
clap = { version = "4.5.51", features = ["derive"] }
env_logger = "0.11.8"
async-channel = "2.5.0"

[dev-dependencies]
ntest = "0.9.3"
