[package]
name = "rtunnel"
version = "0.8.0"
edition = "2024"
default-run = "rtunnel"

[features]
debug = []

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.100"
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand_core = { version = "0.6.4", features = ["getrandom", "std"] }
base64 = "0.22.1"
sha2 = "0.10.9"
aes-gcm = { version = "0.10.3", features = ["std"] }
hkdf = { version = "0.12.4", features = ["std"] }
bytes = "1.11.0"
aead = { version = "0.5.2", features = ["std", "bytes"] }
log = "0.4.28"
tokio-util = { version = "0.7.17", features = ["rt"] }
socket2 = "0.6.1"
clap = { version = "4.5.52", features = ["derive"] }
env_logger = "0.11.8"
chrono = "0.4.42"
tokio-rustls = { version = "0.26.4" }
rcgen = "0.14.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[dev-dependencies]
ntest = "0.9.3"
serial_test = "3.2.0"
tempfile = "3.23.0"

[[bin]]
name = "echo-bench"
path = "benchmark/echo-bench.rs"

[[bin]]
name = "echo-server"
path = "benchmark/echo-server.rs"

[[bin]]
name = "echo-client"
path = "benchmark/echo-client.rs"
