[[servers]]

[servers.listen_to]
type = "tls"
subject = "example.com"
addr = "127.0.0.1:2333"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUcxQA22W0VV6BKnRVJmYYyJh2bFAwCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCPaI9X7N/7VdK1Ygg7+
I30jl4EHJOr3iQQM/dybca6m7XMBPNapPBWBU5446dHGv9Q1NM3frb0Zokb64px5
6iKjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IH4wFeKMQqTMrIWpocM8lpd/0wICVcmQIekz6mCFXXZfAiEAjTMOTgx31UKLOJ/y
RyGIWHErnc/AONJC2pksfi97gOM=
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgWvv1g6b15FGN5Thj
u5tLHuN13VDoDAM0udgdbNCQP+qhRANCAAQj2iPV+zf+1XStWIIO/iN9I5eBByTq
94kEDP3cm3Gupu1zATzWqTwVgVOeOOnRxr/UNTTN3629GaJG+uKceeoi
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUBj2NDY3Y0zugUEk3HfsSi59PG88wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL5abGPDWZPnGPURomJ1
YgcYaoVWzQ/PMFCZHAr0zEVPNIIhwPO+EdVjO9pPnUMRmLiNFWrk22+a86/UYqKs
hb6jGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IEx0uhhomIoxhvXabIoYyry+WhAsigVVWU+NNs75Hf68AiEAkO89zpKz/KTy+LXw
8eRS1O04GENXbeAyOSc/gClr/M8=
-----END CERTIFICATE-----
"""

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 10

[clients.connect_to]
type = "tls"
subject = "example.com"
addr = "127.0.0.1:2333"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUBj2NDY3Y0zugUEk3HfsSi59PG88wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL5abGPDWZPnGPURomJ1
YgcYaoVWzQ/PMFCZHAr0zEVPNIIhwPO+EdVjO9pPnUMRmLiNFWrk22+a86/UYqKs
hb6jGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IEx0uhhomIoxhvXabIoYyry+WhAsigVVWU+NNs75Hf68AiEAkO89zpKz/KTy+LXw
8eRS1O04GENXbeAyOSc/gClr/M8=
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgEDbhtOKH4MMFpfFs
7EBxK6WqUXR0MlzEUj208LgvT56hRANCAAS+Wmxjw1mT5xj1EaJidWIHGGqFVs0P
zzBQmRwK9MxFTzSCIcDzvhHVYzvaT51DEZi4jRVq5NtvmvOv1GKirIW+
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUcxQA22W0VV6BKnRVJmYYyJh2bFAwCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCPaI9X7N/7VdK1Ygg7+
I30jl4EHJOr3iQQM/dybca6m7XMBPNapPBWBU5446dHGv9Q1NM3frb0Zokb64px5
6iKjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IH4wFeKMQqTMrIWpocM8lpd/0wICVcmQIekz6mCFXXZfAiEAjTMOTgx31UKLOJ/y
RyGIWHErnc/AONJC2pksfi97gOM=
-----END CERTIFICATE-----
"""

