[[servers]]

[servers.listen_to]
type = "quic"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYTCCAQagAwIBAgIUd9pTD2NdZlquDRZl4i7UOF6Qw3owCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCScXGCwh3etMtnohsur
qYonXhScdNfLxqxjDyQRDoVfgvW5lrmm8Sczw7CCduMxyHOutqIVjTTDMTKs+hdF
1+yjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0kAMEYC
IQC5AEK1bLKcIlxcmcT0rO95lIaQLNfr0RBwg/0XYTct1gIhAMDzy5D05M8vekQL
7KDzFFpGkRr8+FTzSbYmfPiu5uuw
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgYYRW7edSz8s9SMeS
4JaYmqRo6keDcmcCEOZsil+UWSGhRANCAAQknFxgsId3rTLZ6IbLq6mKJ14UnHTX
y8asYw8kEQ6FX4L1uZa5pvEnM8OwgnbjMchzrraiFY00wzEyrPoXRdfs
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYTCCAQagAwIBAgIUWKqrWTD7gIb705d0v79Apm8C48swCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGA/P/QucnytWXdT1mCX
Bh+sraw+N8gya32erj/mguVSdOjVGI7kUXh6fGc9BKSpfdXej9tbKRqQBU1dyMQp
LumjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0kAMEYC
IQDXh8uK/ia6ZF+4T+Qs1n+/bbfgGHG58rRUx5GRQPCyCQIhAOCSweUIlpqFLsQz
+NHNJWNOYcDnNK73n7IlY5eahESn
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "quic"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYTCCAQagAwIBAgIUWKqrWTD7gIb705d0v79Apm8C48swCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGA/P/QucnytWXdT1mCX
Bh+sraw+N8gya32erj/mguVSdOjVGI7kUXh6fGc9BKSpfdXej9tbKRqQBU1dyMQp
LumjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0kAMEYC
IQDXh8uK/ia6ZF+4T+Qs1n+/bbfgGHG58rRUx5GRQPCyCQIhAOCSweUIlpqFLsQz
+NHNJWNOYcDnNK73n7IlY5eahESn
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgTsRyz0OsLBQGfVIw
8/ZCkswMvA1wHt4w+LjCL2JbJeqhRANCAARgPz/0LnJ8rVl3U9ZglwYfrK2sPjfI
Mmt9nq4/5oLlUnTo1RiO5FF4enxnPQSkqX3V3o/bWykakAVNXcjEKS7p
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYTCCAQagAwIBAgIUd9pTD2NdZlquDRZl4i7UOF6Qw3owCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCScXGCwh3etMtnohsur
qYonXhScdNfLxqxjDyQRDoVfgvW5lrmm8Sczw7CCduMxyHOutqIVjTTDMTKs+hdF
1+yjGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0kAMEYC
IQC5AEK1bLKcIlxcmcT0rO95lIaQLNfr0RBwg/0XYTct1gIhAMDzy5D05M8vekQL
7KDzFFpGkRr8+FTzSbYmfPiu5uuw
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

