[[servers]]

[servers.listen_to]
type = "quic"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhRU/iNtiVNg+Qs7WQe6hzaa9OZRkzAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAOgFdNmeJ/SLNeVC6v/q5HOerVB+xAtZvDtTtMPM5XjDoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQA2ZQIgaUNbuWeenkgq
tY4mT/JoRIWwKcNDD+mMO0LgeILApL/f87LDz46TZR2DKtXfI9claTdvKo1g/OUA
7ygK
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIPV+uiWAQm93VkQX9Izo0g1ZIxIq8vuxq2Uaz3aKsR0n
gSEA6AV02Z4n9Is15ULq/+rkc56tUH7EC1m8O1O0w8zleMM=
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQb4D3/0UdOZqSVxojSm/GuAPeKNDAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAEz99fkMBTf7hBbwMXPoJy8G31H5tsO74m03RGJqkeVDoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQCL4kKYHf3/31aR/E7r
ujiPWYX0tv9SFqbfnwL0FcGULq0QBY7blr70HgEB5inJgRh9bBdvb39yETeyoXmO
K/oO
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "quic"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQb4D3/0UdOZqSVxojSm/GuAPeKNDAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAEz99fkMBTf7hBbwMXPoJy8G31H5tsO74m03RGJqkeVDoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQCL4kKYHf3/31aR/E7r
ujiPWYX0tv9SFqbfnwL0FcGULq0QBY7blr70HgEB5inJgRh9bBdvb39yETeyoXmO
K/oO
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIG5PJEAzSeuAHqszdnYMvOCba9RSjOqcn6s02ZGOs8Xw
gSEATP31+QwFN/uEFvAxc+gnLwbfUfm2w7vibTdEYmqR5UM=
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhRU/iNtiVNg+Qs7WQe6hzaa9OZRkzAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAOgFdNmeJ/SLNeVC6v/q5HOerVB+xAtZvDtTtMPM5XjDoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQA2ZQIgaUNbuWeenkgq
tY4mT/JoRIWwKcNDD+mMO0LgeILApL/f87LDz46TZR2DKtXfI9claTdvKo1g/OUA
7ygK
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

