[[servers]]

[servers.listen_to]
type = "tls-tcp"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUHld+tEEGdGYYar5nPJHYVGsPbDowCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJCZoe63ZB4zh6wFSApg
MmYOHdyZJrM0oPEFBkU7FEH+eJVx53GNErXvdW27ZagBtPrnEJKtQmvgZ6fJBy1i
y2ujGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IDgVdzPA5RIKmh7D9jJqnOyPB/TP5Mq0zFwcwFd8l43FAiEApQSQ0DqkCA1gILeb
0KCRa0U3LVFlCjcQl808OeJRmFc=
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgtzoDv5MEY96KQY29
qZA8IJJcx7miFfSEgw/WjWgE8fehRANCAASQmaHut2QeM4esBUgKYDJmDh3cmSaz
NKDxBQZFOxRB/niVcedxjRK173Vtu2WoAbT65xCSrUJr4GenyQctYstr
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUSvsONypdhT+vNPid6Obp7QE7aOQwCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEDkSsK3yq0jihhn7WGN
sTsnhq4tnN3f0NZ8iAdgumP3xCJ71Cn/1SLuLGa2te2orz/IvyLXn7QGMg/bO/xS
dEejGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IGIAX0Grif7gMt9PFDAEj4DN92MKfNul/rtLDStMYDs1AiEAvZxR/cqJpXhkyOU9
J6ajhDnim7Ghaa38o5/a6huNB+M=
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "tls-tcp"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUSvsONypdhT+vNPid6Obp7QE7aOQwCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEDkSsK3yq0jihhn7WGN
sTsnhq4tnN3f0NZ8iAdgumP3xCJ71Cn/1SLuLGa2te2orz/IvyLXn7QGMg/bO/xS
dEejGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IGIAX0Grif7gMt9PFDAEj4DN92MKfNul/rtLDStMYDs1AiEAvZxR/cqJpXhkyOU9
J6ajhDnim7Ghaa38o5/a6huNB+M=
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgKftiONxTw2Cupc+d
OdR1ld/4krmF2WtxwY8HCkfwhOqhRANCAARA5ErCt8qtI4oYZ+1hjbE7J4auLZzd
39DWfIgHYLpj98Qie9Qp/9Ui7ixmtrXtqK8/yL8i15+0BjIP2zv8UnRH
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUHld+tEEGdGYYar5nPJHYVGsPbDowCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJCZoe63ZB4zh6wFSApg
MmYOHdyZJrM0oPEFBkU7FEH+eJVx53GNErXvdW27ZagBtPrnEJKtQmvgZ6fJBy1i
y2ujGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IDgVdzPA5RIKmh7D9jJqnOyPB/TP5Mq0zFwcwFd8l43FAiEApQSQ0DqkCA1gILeb
0KCRa0U3LVFlCjcQl808OeJRmFc=
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

