[[servers]]

[servers.listen_to]
type = "plain-tcp"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "plain-tcp"
addr = "127.0.0.1:2333"

