[[servers]]

[servers.listen_to]
type = "tls_tcp"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQz/5/R9ZUOWe2TEHFIQtWwqmFKxDAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAP0/57bm4N70DKCC53jAt3Comnt2Pt0W2xrjCwnXMyjBoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQBhs1TEHy/PElyUykDk
teZD1DWtqa1WolP5aUbPBTmMWthVvWrAboJlhc651Ovlf4Tp1PSQFQrohRWOrBsk
7WkA
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIHwTrm7cEHcJaYCxT0MBD0Yvz29mIzRWQ06apjnGLxjv
gSEA/T/ntubg3vQMoILneMC3cKiae3Y+3RbbGuMLCdczKME=
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQPaY+AC90hgzIuZkmgMpudivotGjAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAN7TpILn+Z339+zPBr+TmP4E/WiIN/A/9jt8fsvPU6PIoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQDH+GstqHZzZrB1ZsOe
WoSCaQ+3S8cPP/aUsNTVv+NnAET2hC/Gc8NfOQmBBHDD5dKWnjF1hAfErOXblol/
1DsD
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "tls_tcp"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQPaY+AC90hgzIuZkmgMpudivotGjAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAN7TpILn+Z339+zPBr+TmP4E/WiIN/A/9jt8fsvPU6PIoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQDH+GstqHZzZrB1ZsOe
WoSCaQ+3S8cPP/aUsNTVv+NnAET2hC/Gc8NfOQmBBHDD5dKWnjF1hAfErOXblol/
1DsD
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIKpsZgA/7WsaukzIwd62LQYJ+6nADdYYPyoI8lxPL1c+
gSEA3tOkguf5nff37M8Gv5OY/gT9aIg38D/2O3x+y89To8g=
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBHzCB0qADAgECAhQz/5/R9ZUOWe2TEHFIQtWwqmFKxDAFBgMrZXAwITEfMB0G
A1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80
MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2Vy
dDAqMAUGAytlcAMhAP0/57bm4N70DKCC53jAt3Comnt2Pt0W2xrjCwnXMyjBoxow
GDAWBgNVHREEDzANggtleGFtcGxlLmNvbTAFBgMrZXADQQBhs1TEHy/PElyUykDk
teZD1DWtqa1WolP5aUbPBTmMWthVvWrAboJlhc651Ovlf4Tp1PSQFQrohRWOrBsk
7WkA
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

