[[servers]]

[servers.listen_to]
type = "tls_tcp"
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUfaJvf2iuIX2dE3Vf6kYrSfN2cc4wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFQ07Mpi+pmLTPJEzmKd
ISOzU8h7qX526v/o49inhOzme45zEmA0S4i1ei5lRaeu9JKcdxRI2617KGdxq4bj
62ajGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IQC2VvkVJvDaoS1pbTsOkH3/cO3TP0WqUW1Vih+whsfGugIgbSrwB84BZzFwfeW9
Uv0OBVFqhGSAPTscauu7XDlQKmQ=
-----END CERTIFICATE-----
"""
server_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgr7pY+qxeQykITeO6
FMSZ2dXCJ3xHPf5aSKhNkEpTm2KhRANCAARUNOzKYvqZi0zyRM5inSEjs1PIe6l+
dur/6OPYp4Ts5nuOcxJgNEuItXouZUWnrvSSnHcUSNuteyhncauG4+tm
-----END PRIVATE KEY-----
"""
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUXyS5G3YCRVeYXFmvtnoCx5Zpyp0wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDibpi2MSmFCk7vpb0Un
owZeBntJtKXZV8oA4g0Edp4ub8cdHAd37iCUCfTnZ9kK0AaqCtYNy5I3dEJc/bua
1G+jGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IGw3NpYveNQQOUmiJ+Dac+mZsDlSV6h2wjLylKUEbnDfAiEA4nYwDXM3Ie5VmZ4l
rZoc7w0/grON9S9YawStk+cK9bw=
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

[[servers.services]]
listen_to = "tcp://0.0.0.0:2334"
connect_to = "tcp://127.0.0.1:2335"

[[clients]]
allowed_addresses = ["tcp://127.0.0.1:2335"]
idle_connections = 20

[clients.connect_to]
type = "tls_tcp"
client_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUXyS5G3YCRVeYXFmvtnoCx5Zpyp0wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDibpi2MSmFCk7vpb0Un
owZeBntJtKXZV8oA4g0Edp4ub8cdHAd37iCUCfTnZ9kK0AaqCtYNy5I3dEJc/bua
1G+jGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IGw3NpYveNQQOUmiJ+Dac+mZsDlSV6h2wjLylKUEbnDfAiEA4nYwDXM3Ie5VmZ4l
rZoc7w0/grON9S9YawStk+cK9bw=
-----END CERTIFICATE-----
"""
client_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/X4lvtVo4kcebU/o
rCewxmLYLEbqVDkHapXrZQz4nUWhRANCAAQ4m6YtjEphQpO76W9FJ6MGXgZ7SbSl
2VfKAOINBHaeLm/HHRwHd+4glAn052fZCtAGqgrWDcuSN3RCXP27mtRv
-----END PRIVATE KEY-----
"""
server_cert = """
-----BEGIN CERTIFICATE-----
MIIBYDCCAQagAwIBAgIUfaJvf2iuIX2dE3Vf6kYrSfN2cc4wCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAw
MDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWdu
ZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFQ07Mpi+pmLTPJEzmKd
ISOzU8h7qX526v/o49inhOzme45zEmA0S4i1ei5lRaeu9JKcdxRI2617KGdxq4bj
62ajGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUC
IQC2VvkVJvDaoS1pbTsOkH3/cO3TP0WqUW1Vih+whsfGugIgbSrwB84BZzFwfeW9
Uv0OBVFqhGSAPTscauu7XDlQKmQ=
-----END CERTIFICATE-----
"""
subject = "example.com"
addr = "127.0.0.1:2333"

